[build]
  base = "MIT1/frontend"
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
